name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32OlcbHub, ESP32OlcbHub-iopcb]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'release/v4.2'
      - name: Build
        run: |
          if [ "${{ matrix.target }}" == "ESP32OlcbHub-iopcb" ]; then
            cat >>sdkconfig.defaults <<CFG_UPDATE
CONFIG_FACTORY_RESET=39
CONFIG_USER_BUTTON=36
CFG_UPDATE
          fi
          source ~/esp/esp-idf/export.sh
          idf.py reconfigure
          idf.py app
          idf.py size
          mkdir binaries
          cp build/ESP32OlcbHub.bin binaries
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
