name: Build

on: [push]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32OlcbHub, ESP32OlcbHub-iopcb]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'release/v4.2'
      - name: Update config for IO PCB
        if: ${{ matrix.target == 'ESP32OlcbHub-iopcb' }}
        uses: DamianReeves/write-file-action@master
        with:
          path: sdkconfig.defaults
          contents: |
            CONFIG_FACTORY_RESET=39
            CONFIG_USER_BUTTON=36
          write-mode: append
      - name: Build
        run: |
          cat sdkconfig.defaults
          source ~/esp/esp-idf/export.sh
          idf.py reconfigure
          idf.py app
          idf.py size
          mkdir binaries
          cp build/ESP32OlcbHub.bin binaries
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
